### ISSUE TITLE
Address data no longer available in site request response

### ISSUE THREAD

**Issue by jazaval** [mrdave-dev/amazon-baby-registry-gift-list-export#2]
`br-tyl-details-wrapper` element has been renamed to `br-tyl-gift-details`, however address data is no longer available in the anywhere in the request response. 

Updating `br-tyl-details-wrapper` with `br-tyl-gift-details` in the script will at least still give you an export with giver name, date of purchase, and product name.

**Comment by mrdave-dev** [comment]
My bad, I hadn't seen this issue until now. I'll put this on my list of todos and take a look

**Comment by mrdave-dev** [comment]
I think [this PR](https://github.com/mrdave-dev/amazon-baby-registry-gift-list-export/pull/3) may have fixed the issue. Can you take a look and confirm?

**Comment by bloewe** [comment]
Major time saver! Thank you. 
On my end, it's pulling complete addresses 75% of the time. The rest is missing city or if street has a direction ahead of it, the street name.

Example Return: 130 E VT, 05301
instead of Address - Direction - Street name - city - State - Zip

**Comment by mrdave-dev** [comment]
@bloewe I'll take a look this week. My guess is that I just forgot part of the address response. The script is super brittle since it relies on Amazon's API staying consistent

**Comment by mrdave-dev** [comment]
@bloewe I think I've got a fix in [this PR](https://github.com/mrdave-dev/amazon-baby-registry-gift-list-export/pull/4). Would you mind pulling it down and trying it out on your gift list? 

The issue was my parsing of the address. I was using regex to parse out the address pieces. I've modified the script to take away the whitespace from the HTML element around the address instead. 

I'll merge the PR late this week if no one gets to it

**Comment by mrdave-dev** [comment]
PR is merged! 

You may have to manually update the script by going to https://github.com/mrdave-dev/amazon-baby-registry-gift-list-export/raw/main/gift-list-export.user.js . I've added a update tag that should allow for auto-updates if you have that enabled. 

Closing this issue. Feel free to re-open if the problem persists.
